export enum Category {
  FANTASY = 'FANTASY',
  SCIENCE_FICTION = 'SCIENCE_FICTION',
  MYSTERY = 'MYSTERY',
  THRILLER = 'THRILLER',
  ROMANCE = 'ROMANCE',
  HORROR = 'HORROR',
  HISTORICAL = 'HISTORICAL',
  YOUNG_ADULT = 'YOUNG_ADULT',
  NON_FICTION = 'NON_FICTION',
  RELIGION = 'RELIGION'
}
